# Site settings
title: Kathryn Brown's CV 
description: kb-code's CV
favicon: /assets/img/avatar.png
baseurl: https://kb-code.github.io/resume
url: https://kb-code.github.io/resume
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Kathryn Brown
  title: Full-Stack Developer and Product Manager
  address: Los Angeles, CA
  email: hirekathrynbrown at gmail dot com
  link: https://kathrynbrown.us
  weibo:
  github: kb-code
  linkedin: hirekathrynbrown
  twitter: thatoutdoorkat
  gavatar: /resume/assets/img/avatar.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Folktale
      location: Los Angeles, CA / remote
      title: Developer, Product Manager
      started: 2020
      duration: (2020 - present)
      description: front end developer and co-founder of collaborative storytelling social media site. Responsible for product management from idea to public release, co-lead on programming. The site is built on a PERN stack and utilizes the Tailwind CSS framework. Public release November 2020.
    - work2:
      company: Seed Librarian
      location: Los Angeles, CA
      title: Webmaster, Founder
      started: 2013
      duration: (2013 - present)
      description: Founder and lead developer for a site that lists the locations of seed libraries around the world. The site uses Leaflet.js and a JSON file structure to house the library listings. Top ranked site on Google for queries within its subject topic.
    - work3:
      company: Meteor Multimedia
      location: Los Angeles, CA
      title: Chief Creative Officer
      started: 2003
      duration: (2003 - 2013)
      description: Lead creative designer and developer for digital creative agency specializing in feature film production and small business client services. Services included website development, branding materials (business cards, brochures, logo design, fundraising videos, corporate voiceovers, copywriting, and product photography), and digital strategy consultation. Produced and edited a feature film from concept to distribution over streaming service platform.
  educationHistory:
    - education1:
      organization: Duke University
      location: Durham, NC
      degree: Bachelor
      major: Sociology; Media Studies Certificate
      started: 1997
      duration: (1997 - 2001)
      description: National Merit Scholar. Coursework included Introduction to Computer Science, Statistics and Data Analysis for Social Sciences. 
    - education2:
      organization: Univeristy of California, Riverside
      location: Riverside, CA
      degree: Accelerated Career in Big Data and AI 
      started: 2019
      duration: (2019 - 2019)
      description: Hands-on certification practicum for learning advanced data analysis with Python using Jupyter Notebooks, Pandas, Matplotlib.
    - education3:
      organization: CognitiveClass.ai
      location: online
      degree: Python For Data Science
      started: 2019
      duration: (2019 - 2020)
      description: Received IBM certification in using Python with modern data visualization and analysis tools like Pandas, Matplotlib, PyNum
    - education4:
      organization: Codecademy
      location: online
      degree: Full-Stack Web Developer career track
      started: 2020
      duration: (2020 - 2020)
      description: Completed 6 month certification track in full-stack web development. Completed individual class certifications below - <br> <strong>Introduction to HTML <br> Learn CSS <br> Learn Color Design <br> Learn Responsive Design <br> Introduction to JavaScript <br> Building Interactive Javascript Websites <br> Javascript Errors and Debugging <br> Creating a Front-End Site with React Skill Path <br> Learn Node.js <br> Learn the Command Line <br> Learn Git <br> Learn Sass <br> Navigation Design <br> How to Deploy a Website <br> Testing for Web Development <br> Ansynchronous Javascript <br> Learn Node-SQLite <br> Learn Express - Javascript Unit Testing <br> Create a Website with HTML, CSS, and GitHub Pages Skill Path</strong>
    - education5:
      organization: Codecademy
      location: online
      degree: Data Science career track
      started: 2020
      duration: (2020 - 2020)
      description: Completed 6 month certification track in data science using Python and SQL. Completed individual class certifications below - <br> <strong>Learn SQL <br> Data Analysis with Pandas <br> Data Visualization with Python <br> Web Scraping with Beautiful Soup <br> Regular Expressions Basics <br> How to Clean Data with Python <br> Statistics with Python <br> Statistics with NumPy <br> Learn Python 3 <br> Machine Learning Basics <br> Natural Language Processing <br> Learn D3 <br> How to Transform Tables with SQL <br> How to Analyze Business Metrics with SQL <br> Basics of Blockchain with Python <br> Recursion with Python <br> Implementing Search Algorithms with Python <br> Analyze Data with SQL Skill Path <br> Analyze Financial Data with Python Skill Path <br> Analyze Data with Python Skill Path</strong>
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Basic
    - language3:
      name: Spanish
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: HTML & CSS (Sass, Tailwind)
    - skill2:
      name: JavaScript
    - skill3:
      name: Python
    - skill4:
      name: Data Sci/ML (Pandas, NumPy, MatPlotLib, Seaborn)
    - skill5:
      name: React.js, Node.js
    - skill6:
      name: SQL (SQLite, PostgreSQL)
