# Site settings
title: Kathryn Brown's CV 
description: kb-code's CV
favicon: /assets/img/avatar.png
baseurl: https://kb-code.github.io/resume
url: https://kb-code.github.io/resume
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Kathryn Brown
  title: Full Stack Developer
  address: Los Angeles, CA
  email: hirekathrynbrown at gmail dot com
  link: https://kathrynbrown.us
  weibo:
  github: kb-code
  linkedin: hirekathrynbrown
  twitter: thatoutdoorkat
  gavatar: /resume/assets/img/avatar.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: 
      location: 
      title: Developer
      started: 2012
      duration: ()
      description: description coming soon...
    - work2:
      company: Seed Librarian
      location: Los Angeles, CA
      title: Webmaster, Founder
      started: 2013
      duration: (2013 - present)
      description: Founder and lead developer for a site that lists the locations of seed libraries around the world. The site uses Leaflet.js and a JSON file structure to house the library listings. Top ranked site on Google for queries within its subject topic.
    - work3:
      company: Meteor Multimedia
      location: Los Angeles, CA
      title: Chief Creative Officer
      started: 2003
      duration: (2003 - 2013)
      description: Lead creative designer and developer for digital creative agency specializing in feature film production and small business client services. Services included website development, branding materials (business cards, brochures, logo design, fundraising videos, corporate voiceovers, copywriting, and product photography), and digital strategy consultation. Produced and edited a feature film from concept to distribution over streaming service platform.
  educationHistory:
    - education1:
      organization: Duke University
      location: Durham, NC
      degree: Bachelor
      major: Sociology; Media Studies Certificate
      started: 1997
      duration: (1997 - 2001)
      description: National Merit Scholar. Coursework included Introduction to Computer Science, Statistics and Data Analysis for Social Sciences. 
  languages:
    - language1:
      name: English
      proficiency: Native
    - language2:
      name: French
      proficiency: Basic
    - language3:
      name: Spanish
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: HTML
      percentage: 100%
    - skill2:
      name: JavaScript
      percentage: 70%
    - skill3:
      name: Python
      percentage: 60%
    - skill4:
      name: ReactJS
      percentage: 40%
    - skill5:
      name: SQL
      percentage: 90%
